spring:
  datasource:
    username: testdb
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: psw
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: create

fileRepositoryFolder: C:\Users\paola\Desktop\FileRepository
